name: gala

channels:
  - astropy
  - conda-forge

dependencies:
  - python
  - astropy>=3
  - astropy-helpers
  - numpy
  - cython
  - matplotlib
  - scipy
  - pyyaml
  - IPython
  - jupyter
  - notebook
  - ipykernel
  - gsl
  - pip:
    - nbsphinx
    - sphinx_astropy
    - tqdm
