name: gala

dependencies:
  - python
  - numpy
  - cython
  - gsl
  - pip
  - pip:
    - astropy
    - nbsphinx
    - sphinx_astropy
    - astropy-helpers
    - tqdm
    - matplotlib
    - scipy
    - pyyaml
    - IPython
    - jupyter
    - notebook
    - ipykernel
