name: nix-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 13 * * 1"  # Mondays @ 9AM Eastern

jobs:
  build:
    name: "py${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        os: [ubuntu-18.04, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Mac:
      - name: Setup Mac
        if: runner.os == 'macOS'
        run: |
          brew install gsl

      # Ubuntu:
      - name: Setup Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install gsl-bin libgsl0-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox  # This relies on tox-gh-actions